### ISSUE TITLE
Retrieve individual predictions from SLiME

### ISSUE THREAD

**Issue by capjamesg** [aliasgharkhani/SLiMe#2]
Hello there! I am an engineer at Roboflow. I am working on adding SLiME into [Autodistill](https://github.com/autodistill/autodistill), our framework for using foundation models like SLiME to label data.

I would like to run inference on images one-by-one instead of using a whole folder of images on which to run inference through `trainer.test()`. Is there a way in which I can run inference on a single image?

**Comment by aliasgharkhani** [comment]
You can put images one by one in that folder and get their predictions
or you can modify the code to get the test image name instead of the test folder and only segment the passed image
