### ISSUE TITLE
The difference between official diffusers and SLiMe’s implementation

### ISSUE THREAD

**Issue by Xudangliatiger** [aliasgharkhani/SLiMe#4]
Anything different between the official diffusers and your implementation? is that OK to simply use the diffuser with pip install

**Comment by aliasgharkhani** [comment]
We have made some changes in the code to be able to extract attention maps from the UNet. So if you use the diffusers with pip install it won't work

**Comment by Xudangliatiger** [comment]
Thanks for sharing the information. Could you share the specific files have been modified? I would like to use the updated diffusers.

By the way, the work is solid, thanks for sharing the codes.

**Comment by aliasgharkhani** [comment]
I have modified the following files:
diffusers/models/attention.py lines: 294 and 312
diffusers/models/attention_processor.py lines: 387 and 651
