### ISSUE TITLE
Test IoU all zero, except background class

### ISSUE THREAD

**Issue by ahmadsadeed** [aliasgharkhani/SLiMe#5]
I run the training for CelebAMask-HQ using 10 images and got the following IoUs:

Test metric             DataLoader 0
test background iou_epoch   0.8686891794204712
   test brow iou_epoch      0.5312750935554504
  test cloth iou_epoch      0.6570164561271667
   test ear iou_epoch       0.6135838627815247
   test eye iou_epoch       0.6512457132339478
   test hair iou_epoch      0.8488448858261108
  test mouth iou_epoch      0.8260374069213867
   test neck iou_epoch      0.7992124557495117
   test nose iou_epoch      0.7965044379234314
   test skin iou_epoch      0.8852006793022156
────────────────────────────────────────────────

When I run the test, I get all zeros:
```
python -m src.main --dataset celeba 
                   --part_names background skin eye mouth nose brow ear neck cloth hair 
                   --checkpoint_dir "${CHECKPOINT_DIR}" 
                   --test_data_dir $DATADIR/celeba/test 
                   --save_test_predictions
```

Test metric             DataLoader 0

test background iou_epoch   0.3147919178009033
   test brow iou_epoch              0.0
  test cloth iou_epoch              0.0
   test ear iou_epoch               0.0
   test eye iou_epoch               0.0
   test hair iou_epoch              0.0
  test mouth iou_epoch              0.0
   test neck iou_epoch              0.0
   test nose iou_epoch              0.0
   test skin iou_epoch              0.0

Could you help debug this issue? My goal is to see segmentations overlaid on images and eventually save these segmentations as numpy arrays.

**Comment by aliasgharkhani** [comment]
Do you pass a valid path to --checkpoint_dir? Which should be the folder path where your trained weights are.
