### ISSUE TITLE
Extract the numpy arrays of each segmented part 

### ISSUE THREAD

**Issue by sivaji123256** [aliasgharkhani/SLiMe#6]
Hi @hamarneh @aliasgharkhani ,
Thanks for the great work.I was able to implement on custom data.But I was trying to train and test at the original image size not at default of 512,Currently my original image size is 1920*1080.Also, during testing ,I want to extract the numpy arrays of each segmented part in the mask.How can I modify the code?Thanks in advance.

**Comment by aliasgharkhani** [comment]
Hi,
It is not possible to train in that resolution. SLiMe only works with 512x512.
You can save the mask generated here https://github.com/aliasgharkhani/SLiMe/blob/0df6cc57b8c45c6658fb7abcecf3cc4b9d7c340e/src/slime.py#L371 in numpy format.
