### ISSUE TITLE
RuntimeError: expected scalar type float but found long int

### ISSUE THREAD

**Issue by wxqlab** [aliasgharkhani/SLiMe#7]
Hi, when I train the model on CelebAMask-HQ, I find the error on the line:
pixel_weights = torch.where(num_pixels > 0, num_pixels.sum() / num_pixels, 0)

Please help me debug this issue?

**Comment by aliasgharkhani** [comment]
Changing it with
pixel_weights = torch.where(num_pixels > 0, num_pixels.sum() / num_pixels, 0)
should resolve your problem.
please pull the code, as I have modified that line
