### ISSUE TITLE
Segmentation  IOU not improving 

### ISSUE THREAD

**Issue by sivaji123256** [aliasgharkhani/SLiMe#8]
Hi @hamarneh @aliasgharkhani ,
Thanks for the great work. I was trying to segment the parts of the animals.Head and Body were segmenting well.But,I couldn't segment the ears in more than 75% of test images.I have labelled them clearly.But one thing to be noted is they are very small.You have mentioned that SLiMe may fail for small objects.But,I want to understand the effect of the following parameters during the training.Can you pls elobarate the affect of the below args you mentioned in the args.py?Also, any other suggestions to fix thsi will be highly useful.Thanks in advance.
 parser.add_argument("--train_mask_size", type=int, default=64)
 parser.add_argument("--train_t", nargs="+", type=int, default=[5, 100])
 parser.add_argument("--self_attention_loss_coef", type=float, default=1.0)
 parser.add_argument("--sd_loss_coef", type=float, default=0.005)
 parser.add_argument("--num_patchs_per_side", type=int, default=2)
 parser.add_argument("--patch_size", type=int, default=400)
 parser.add_argument("--patch_threshold", type=float, default=0.2)
 parser.add_argument("--test_t", nargs="+", type=int, default=[100])
 parser.add_argument("--test_mask_size", type=int, default=512)

**Comment by aliasgharkhani** [comment]
If you look at code you should be able to understand the effect of these arguments. Also for this issue, we don’t have a solution yet, unless you find a text to image model which uses cross attention maps and has larger cross attention maps.
